apiVersion: v1
kind: Service
metadata:
  name: golang-app-2-service
  labels:
    {{- include "golang-app-2.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      appProtocol: http
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "golang-app-2.selectorLabels" . | nindent 4 }}
