apiVersion: v1
kind: Service
metadata:
  name: golang-app-2
  labels:
    {{- include "golang-app-2.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: http
  selector:
    {{- include "golang-app-2.selectorLabels" . | nindent 4 }}
