apiVersion: v1
kind: Service
metadata:
  name: golang-app-2-service
  labels:
    {{- include "golang-app-2.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "golang-app-2.selectorLabels" . | nindent 4 }}
