apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    #ARGO CD IMAGE UPDATER  --- change it
    argocd-image-updater.argoproj.io/image-list: golang-app-first=019088769801.dkr.ecr.us-east-1.amazonaws.com/golang-app-first
    argocd-image-updater.argoproj.io/golang-app-first.update-strategy: latest
    argocd-image-updater.argoproj.io/golang-app-first.allow-tags: regexp:^prod-[0-9a-zA-Z]+$

    #ARGO CD IMAGE UPDATER  --- change it
  name: golang-app-1-prod
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    helm:
      parameters:
        - name: image.tag
          value: $ARGOCD_APP_REVISION
        - name: environment
          value: preprod
      valueFiles:
        - values.yaml
    path: golang-app-1-prod
    repoURL: https://github.com/mojeico/golang-helm.git


  syncPolicy:
    automated: {}
