config:
  registries:
    - name: ECR
      api_url: https://019088769801.dkr.ecr.us-east-1.amazonaws.com
      prefix: 019088769801.dkr.ecr.us-east-1.amazonaws.com
      default: true
      ping: yes

      # FOR LOCAL (DOCKER) CLUSTER
      #credentials: secret:argocd/git-creds

      # For EKS CLUSTER
      credentials: ext:/scripts/ecr-login.sh  #script name should match here and in authScripts
      credsexpire: 5h

  logLevel: debug

image:
  tag: "v0.12.2"

# For EKS CLUSTER
authScripts:
  enabled: true
  scripts:
    ecr-login.sh: |
      #!/bin/sh
      export AWS_ACCESS_KEY_ID=AKIAQI4OHQME2LHJ54XM
      export AWS_SECRET_ACCESS_KEY=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
      
      aws ecr --region us-east-1 get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d