apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    #ARGO CD IMAGE UPDATER  --- change it




    #ARGO CD IMAGE UPDATER  --- change it
    argocd-image-updater.argoproj.io/image-list: golang-app-first=019088769801.dkr.ecr.us-east-1.amazonaws.com/golang-app-first
    argocd-image-updater.argoproj.io/golang-app-first.update-strategy: latest
    argocd-image-updater.argoproj.io/golang-app-first.allow-tags: regexp:^dev-[0-9a-zA-Z]+$




    #ARGO CD IMAGE UPDATER  --- change it
  name: golang-app-1-dev
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
        - values/values-dev.yaml
    path: golang-app-1
    repoURL: https://github.com/mojeico/golang-helm.git


  syncPolicy:
    automated: {}
