apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: golang-app-second=019088769801.dkr.ecr.us-east-1.amazonaws.com/golang-app-second

    # work with golang-app-first:v1.1.2 and with v1.1.2-snd but ignore -snd
    #argocd-image-updater.argoproj.io/golang-app-first.update-strategy: semver

    argocd-image-updater.argoproj.io/golang-app-second.force-update: "true"

    # work with golang-app-first:v1.1.2 and with v1.1.2-snd but NOT  ignore -snd
    argocd-image-updater.argoproj.io/golang-app-second.allow-tags: regexp:v[0-9]\.[0-9]\.[0-9]-dev

  name: golang-app-2-dev
  namespace: argocd

status:
  sourceType: Helm

spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: golang-app-2
    repoURL: https://github.com/mojeico/golang-helm.git
  syncPolicy:
    automated: {}

